### ISSUE TITLE
Install with conda

### ISSUE THREAD

**Issue by liaochenlanruo** [zhangyumeng1sjtu/T4SEfinder#1]
Hi there, which version of python it depends on and would you like to submit a conda recipe so that people can install the software with conda?

**Comment by zhangyumeng1sjtu** [comment]
python 3.7+ is ok. We will submit the python package to PyPI. Thus, you can use pip to  install the software more easily.

**Comment by liaochenlanruo** [comment]
How to run the software after installed by "pip install T4SEfinder". The main.py can be not found anywhere. Should I download the scripts after running "pip install T4SEfinder"?

**Comment by zhangyumeng1sjtu** [comment]
Yeah. It's necessary to clone the repository first for usage.
